spring.config.activate.on-profile=prod

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
